### ISSUE TITLE
AppController not found

### ISSUE THREAD

**Issue by HLenin** [Dinocanid/Mysidia-Deluxe#10] opened 2021-02-18 02:35 UTC
This issue is really game-breaking.
I can't open a thing due to the appcontroller missing. I tried looking for it, but it's a ton of files. I don't really know anything about mysidia, so any help would be appreciated!

**Comment by awjudd** [comment] 2021-02-25 13:37
This is a duplicate of #7

**Closed as completed by awjudd** 2021-02-25 13:37 UTC
